apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - couchdb-pvc.yaml
  - app-pvc.yaml
  - config.yaml
  - secrets.yaml
  - couchdb-deployment.yaml
  - couchdb-service.yaml
  - app-deployment.yaml
  - app-service.yaml
